### ISSUE TITLE
Waiting for IP...

### ISSUE THREAD

**Issue by harrisonj94** [StefanZ8n/packer-ws2022#1]
```
==> ws2022.vsphere-iso.ws2022: Customizing hardware...
==> ws2022.vsphere-iso.ws2022: Mounting ISO images...
==> ws2022.vsphere-iso.ws2022: Adding configuration parameters...
==> ws2022.vsphere-iso.ws2022: Starting HTTP server on port 8771
==> ws2022.vsphere-iso.ws2022: Set boot order temporary...
==> ws2022.vsphere-iso.ws2022: Power on VM...
==> ws2022.vsphere-iso.ws2022: Waiting 3s for boot...
==> ws2022.vsphere-iso.ws2022: HTTP server is working at OMITTED
==> ws2022.vsphere-iso.ws2022: Typing boot command...
==> ws2022.vsphere-iso.ws2022: Waiting for IP...
```

I am getting this output, as I dont use DHCP, how can I get this to work as it will never assign an IP to the VM.

**Comment by StefanZ8n** [comment]
Hi Joe,
at this step packer tries to get the IP of the VM from vSphere. If you don't have a DHCP on your network you'd need to configure a static IP on the VM, e.g. by changing the `unattended.xml`. Maybe you can also rely on APIPA addressing if vCenter also detects these IPs.
